package org.resk.lesson4.solution12;

import org.resk.second.solution32.Solution32;

import java.io.*;
import java.util.Scanner;

public class Solution12{
    static Scanner sc = new Scanner(System.in);
    public static void main(String[] args) throws FileNotFoundException {
        String filename = sc.next();
        File file = new File(filename);

        //Generated by python script
        try (BufferedInputStream br = new BufferedInputStream(new FileInputStream(file))){
            while (br.available() > 0){
                System.out.print((char)br.read());
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
        sc.close();
    }
}