package org.resk.lesson5.solution1;

import java.util.SplittableRandom;
import java.util.function.BinaryOperator;
import java.util.stream.Stream;

public class Solution1{
    public static void main(String[] args)
    {
        //Generated by python script

        Stream<String> streamR = Stream.of("Первый", "Элемент", "В", "Данном", "Потоке");
        Stream<String> streamF = Stream.of("Другой", "Первый", "Элемент", "В", "Потоке");
        System.out.println("Первый элемент: " + firstElementByReduce(streamR));
        System.out.println("Превый элемент: " + firstElementByFindFirst(streamF));

    }
    public static String firstElementByReduce(Stream<String> stream) {
        return stream.reduce(new BinaryOperator<String>() {
            @Override
            public String apply(String s, String s2) {
                return s ;
            }
        }).get();
    }


    public static String firstElementByFindFirst(Stream<String> stream) {
        return  stream.findFirst().get() ;
    }
}