package org.resk.first.solution41;

import java.io.IOException;

public class Solution41{
    public static void main(String[] args) {
        //Generated by python script
    }
        static class MyException extends NullPointerException{}
        static class MyException2 extends IndexOutOfBoundsException {}
        static class MyException3 extends IOException {}
        static class MyException4 extends NoSuchFieldException {}

}